   unsigned int          run;
   unsigned int          luminosityBlock;
   unsigned int          bunchCrossing;
   unsigned int          orbitNumber;
   Double_t        mmumu;
   Bool_t          isOS;
   Double_t        DRmumu;
   Double_t        xsweight;
   Float_t         met;
   Int_t           bxspread1;
   Int_t           bxspread2;
   Bool_t          isL1MuMatched1;
   Bool_t          isL1MuMatched2;
   Int_t           nstub1;
   Int_t           nstub2;
   short stub1Station1;
   short stub2Station1;
   short stub3Station1;
   short stub4Station1;
   short stub1Station2;
   short stub2Station2;
   short stub3Station2;
   short stub4Station2;
   short stub1Bx1;
   short stub2Bx1;
   short stub3Bx1;
   short stub4Bx1;
   short stub1Bx2;
   short stub2Bx2;
   short stub3Bx2;
   short stub4Bx2;
   Float_t        genpt1;
   Float_t        genpt2;
   Double_t        pt1;
   Double_t        eta1;
   Double_t        phi1;
   Short_t         charge1;
   Short_t         qual1;
   Short_t         dxy1;
   short         charge1_short;
   short         qual1_short;
   short         dxy1_short;
   Double_t        pt2;
   Double_t        eta2;
   Double_t        phi2;
   Short_t         charge2;
   Short_t         qual2;
   Short_t         dxy2;
   short         charge2_short;
   short         qual2_short;
   short         dxy2_short;

